### ISSUE TITLE
support DEFINE (Virtuoso SPARQL extension)

### ISSUE THREAD

**Issue by christopher-johnson** [RubenVerborgh/SPARQL.js#26]
I am using Virtuoso's DEFINE input:inference clause and would like to pass this through in a TPF query.  

The syntax is Define ::=  'DEFINE' QNAME (QNAME | Q_IRI_REF | String )
See https://github.com/openlink/virtuoso-opensource/blob/master/libsrc/Wi/sparql_core.c for all configuration options.

Thanks!

**Comment by RubenVerborgh** [comment]
Hi @christopher-johnson, thanks for the request.

However, I'm hesitant to add something that is non-standard. Do you have documentation somewhere of what `DEFINE` does? (A quick Google search was inconclusive.)

**Comment by christopher-johnson** [comment]
DEFINE sends configuration options to the SPARQL compiler.  It is actually a very useful extension of Virtuoso that does a lot.  See line 820 in sparql_core.c for the function definition.  RE: standards, I understand your point, but the TPF metadata implementation is built around Virtuoso's non-standard COUNT function, so ...

**Comment by RubenVerborgh** [comment]
I'd like to understand your use case a bit better. So you want to be able to use `DEFINE` in SPARQL queries parsed by the JavaScript parser, but you send them to Virtuoso afterwards? I'm a bit confused by that, because a) only the TPF _client_ uses the SPARQL.js parser, but this client does _not_ interface with Virtuoso b) the TPF _server_ does interface with Virtuoso (well, SPARQL endpoints in general), but does not use the SPARQL.js parser. So in other words, how would a parsed SPARQL query with a DEFINE clause end up in Virtuoso? How would `DEFINE` be passed from a client to a server (given that servers only support triple pattern queries)?

> the TPF metadata implementation is built around Virtuoso's non-standard COUNT(*) function

Note that `COUNT(*)` is standard SPARQL, as you can see in the [SPARQL 1.1 specification](https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#rAggregate). If it were non-standard SPARQL, the SPARQL.js would reject it (assuming no bugs).

> With that being said, maybe it could extend beyond the standard for typical "edge cases"?

That's possible, but I need to understand "typical".  Your answer to the questions above might help me better understand the importance of `DEFINE`, because I don't see the JavaScript–Virtuoso connection at the moment.

**Comment by christopher-johnson** [comment]
Hmm.  My use case is that I am federating DBpedia and Wikidata and comparing taxonomic result sets.  I need reasoning to do transitive queries in Wikidata for multiple property subclass expansion.  Here is a link to my client instance with the test query: http://tinyurl.com/j68m7r4.  The immediate noticeable problem is with the client, a syntax error.  My server is here: http://orbeon-bb.wmflabs.org.  Also, my VIrtuoso instance (with a complete Wikidata dump) is here: http://wdm-rdf.wmflabs.org  I get what you are saying and I had not fully considered that the server only sends a triple pattern.  Perhaps then a static configuration option like "prefixes" in the Server.js is the right solution?  Could a server configuration option be then triggered from the client?

Interesting about `COUNT(*)`.  It is not supported by Blazegraph (Sesame).  Blazegraph needs it to be `COUNT(?s)` AS ?n and will not return Turtle/N3 for `SELECT` aggregates either.

Thank you for your time!

**Comment by RubenVerborgh** [comment]
Thanks, the use case is fully clear now (and interesting, BTW).

> The immediate noticeable problem is with the client, a syntax error.

Indeed. I think this is correct: the client itself is not a Virtuoso endpoint, so it should not support Virtuoso-specific syntax in my opinion.

> Perhaps then a static configuration option like "prefixes" in the Server.js is the right solution?

Yes, I think it is really the server that needs to be configured here.

> Could a server configuration option be then triggered from the client?

_Could_ it be? Yes.

Do I _personally_ think it should be? No. (Here I'm talking from my TPF and REST API background; feel free to disagree.)  I think that the data source should be opaque for the client. I.e., the client just sends queries, and whether the transitive properties are the result of reasoning, or whether they have been materialized before, should not be the client's concern in my opinion.

So I would indeed propose to extend the server configuration in this case, so that this stuff is prepended before queries. (But there are other options. However, assuming a certain endpoint vendor on the client is not my preferred scenario for sustainability.)

> Interesting about COUNT(*). It is not supported by Blazegraph (Sesame). Blazegraph needs it to be COUNT(?s) AS ?n and will not return Turtle/N3 for SELECT aggregates either.

Are you using the latest version of our server (2.0.0+)? There used to be a [bug](https://github.com/LinkedDataFragments/Server.js/pull/22) related to Blazegraph indeed: we were using the non-standard `SELECT COUNT(*)` as opposed to `SELECT (COUNT(*) AS ?c)` and were also not asking for CSV. However, the bug was in the missing `AS ?c`, not in `COUNT(*)`, which should be supported. Could you verify? Thanks!

**Comment by christopher-johnson** [comment]
I have upgraded to the latest version.  This is great, but I still cannot use WDQS directly because of their sitelink formatting problem. 

I am testing your suggested server configuration change that I merged [here](https://github.com/christopher-johnson/Server.js/commit/429bdb8cdbd53f41a903efb5f39c25efbea405b4) now and it is acting very peculiar.  It is difficult to understand why the path inference is not consistently applied when getting with TPF.  

I know that it is partially working though, and I have gotten results that are at least 3 levels deep.  Here is a link using the UI client http://tinyurl.com/zmlhvqm.  I have increased the timeouts for the server in the SparqlDatasource.js and in the client with httpclient, which helps somewhat.  Also, using the CLI seems to be a bit faster, though the inference problem is the same.  [This query ](http://tinyurl.com/zw9lvdy ) shows the  extent of the class hierarchy for the rabbit family (Leporidae).  I am not able to get the fourth or fifth levels.  

If you have any suggestions for tuning, or possible explanations for this behaviour, I would be most grateful!  Thanks again for a very impressive program.

**Comment by RubenVerborgh** [comment]
> I am testing your suggested server configuration change that I merged here

That looks very similar to what I'd do myself. I don't see an issue there.

> It is difficult to understand why the path inference is not consistently applied when getting with TPF.

Given the code, it seems that `DEFINE` is sent out with every query. That would mean the problem lies with the Virtuoso server on the other end.

To confirm that `DEFINE` is sent out every time, I'd add a log statement [here](https://github.com/christopher-johnson/Server.js/blob/429bdb8cdbd53f41a903efb5f39c25efbea405b4/lib/datasources/SparqlDatasource.js#L76).

> Also, using the CLI seems to be a bit faster, though the inference problem is the same.

>  I am not able to get the fourth or fifth levels.

A limitation on the server side?

**Comment by christopher-johnson** [comment]
I have overlooked something obvious (OPTIONAL)  in the query.  It actually works perfectly.  Check this out http://tinyurl.com/jlugfow  I am getting all of the results.  I have also tested with the CLI and this also works well.  I think that this issue can be closed.

**Comment by RubenVerborgh** [comment]
Great, thanks for the feedback. Feel free to add an issue / pull request to the TPF server for the extra functionality.

**Comment by RubenVerborgh** [comment]
BTW Awesome use case :smile:
If you want us to help make some noise about this, don't hesitate to get in touch!
