### ISSUE TITLE
Parsing sparql-10-2-2b.sparql produces results that do not match with sparql-10-2-2b.json

### ISSUE THREAD

**Issue by yamalight** [RubenVerborgh/SPARQL.js#6]
So, parser for some reason omits UNDEF fields for VALUES.

Expected output: 

```json
"type": "values",
"values": [
  {
    "?title": "\"SPARQL Tutorial\"",
    "?book": "{undefined}"
  },
  {
    "?title": "{undefined}",
    "?book": "http://example.org/book/book2"
  }
]
```

Actual output:
```json
"type": "values",
"values": [
  {
    "?title": "\"SPARQL Tutorial\"",
  },
  {
    "?book": "http://example.org/book/book2"
  }
]
```

**Comment by RubenVerborgh** [comment]
Thanks for reporting. The code behaves fine though. The expected output is actually:
```JSON
"values": [
  {
    "?title": "\"SPARQL Tutorial\"",
    "?book": undefined
  },
  {
    "?title": undefined,
    "?book": "http://example.org/book/book2"
  }
]
```

But since `undefined` is not valid JSON (as you can see above), for the tests, we identify the value `undefined` by `"{undefined}"`. This is [restored back](https://github.com/RubenVerborgh/SPARQL.js/blob/v1.0.5/test/SparqlParser-test.js#L76) in the test code.
